eye=imread('eye_orig.jpg');
eye=double(eye(:,:,1));
colormap(gray);
edg=Sobel_log(eye);
imagesc(edg(:,:,1))
sym=DST(eye,5,edg);
imagesc(sym)
eye=imread('eye_orig.jpg');
eye=double(eye(:,:,1));
colormap(gray);
edg=Sobel_log(eye);
imagesc(edg(:,:,1))
sym=DST(eye,5,edg);
imagesc(sym)